/**
 * Utility for handling file uploads to Cloudinary.
 * Works seamlessly with expo-image-picker and expo-document-picker.
 */

interface UploadOptions {
  localUri: string;
  presignedUrl: string; // Now actually a JSON string with Cloudinary credentials
  contentType: string;
  onProgress?: (progress: number) => void;
}

export async function uploadFileToR2({ localUri, presignedUrl, contentType, onProgress }: UploadOptions): Promise<void> {
  return new Promise((resolve, reject) => {
    
    // Parse the Cloudinary payload generated by the backend
    let cloudinaryPayload;
    try {
      cloudinaryPayload = JSON.parse(presignedUrl);
    } catch (e) {
      reject(new Error('Invalid upload credentials received from server.'));
      return;
    }

    const formData = new FormData();
    formData.append('file', {
      uri: localUri,
      type: contentType,
      name: localUri.split('/').pop() || 'upload',
    } as any);
    
    formData.append('api_key', cloudinaryPayload.api_key);
    formData.append('timestamp', cloudinaryPayload.timestamp);
    formData.append('signature', cloudinaryPayload.signature);
    formData.append('public_id', cloudinaryPayload.public_id);

    const xhr = new XMLHttpRequest();

    xhr.upload.onprogress = (event) => {
      if (event.lengthComputable && onProgress) {
        const progress = (event.loaded / event.total) * 100;
        onProgress(Math.round(progress));
      }
    };

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        resolve();
      } else {
        console.error('Cloudinary upload failed:', xhr.responseText);
        
        let errorMessage = 'حدث خطأ أثناء رفع الملف. حاول مرة أخرى'; // Generic fallback
        
        try {
          // Cloudinary format: { "error": { "message": "File size too large..." } }
          const response = JSON.parse(xhr.responseText);
          const cloudMsg = response.error?.message?.toLowerCase() || '';

          if (cloudMsg.includes('format') || cloudMsg.includes('not allowed') || cloudMsg.includes('invalid file')) {
            errorMessage = 'صيغة الملف غير مدعومة. الصيغ المسموحة: JPG, PNG, PDF';
          } else if (cloudMsg.includes('size') || cloudMsg.includes('too large')) {
            errorMessage = 'حجم الملف كبير جدًا. الحد الأقصى 5 ميجابايت';
          }
        } catch (e) {
          // JSON parsing failed, use the fallback message
        }

        reject(new Error(errorMessage));
      }
    };

    xhr.onerror = () => {
      reject(new Error('Network request failed during upload'));
    };

    xhr.open('POST', cloudinaryPayload.url);
    xhr.send(formData);
  });
}
