export const SAFE_USER_SELECT = {
  id: true,
  email: true,
  fullName: true,
  role: true,
  accountMode: true,
  barNumber: true,
  verificationStatus: true,
  preferredLocale: true,
  bio: true,
  isActive: true,
  canActivate: true,
  isOnline: true,
  deletedAt: true,
  createdAt: true,
  updatedAt: true,
  governorateId: true,
  barId: true,
  subscriptionStatus: true,
  subscriptionExpiresAt: true,
  googleId: true,
} as const;
